import SideNav from "../../components/sideNav/sideNav";


export const metadata = {
  title: "Quostize admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <div className="relative h-full flex">
        <div className="w-60 h-full border-r-2 border-black">
          <SideNav />
        </div>
        <div className="grow h-full">
          {children}
        </div>
      </div>
  );
}