import { SessionProvider } from "next-auth/react";
import localFont from "next/font/local"
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
})


export default function RootLayout({ children }) {
  return (
    <SessionProvider>
      <html lang="kr" className={`${pretendard.variable} h-full`}>
        <body className={`h-full font-pretendard`}>
          <div className="h-full">
            {children}
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
